<?php
/**
 * Copyright © Magento2Express. All rights reserved.
 * @author: <mailto:contact@magento2express.com>.
 */

// @codingStandardsIgnoreFile

?>
<?php $configHelper = $block->getModuleConfig(); ?>
<?php $cartPosition = $configHelper->getCartPosition(); ?>
<?php $themeStyle = $configHelper->getThemeStyle(); ?>
<?= /* @escapeNotVerified */ ($themeStyle=='horizontal') ? '<div id="custom-main-container">' : '<div id="custom-main-container-reverse">' ?>
<?php if (($_products = $block->getProductCollection()) && $_products->getSize()): ?>
    <?php $suffix = $block->getNameInLayout(); ?>
    <?php $iterator = 0; ?>
    <?php foreach ($_products->getItems() as $_product): ?>
        <?php $iterator++; ?>
        <?= /* @escapeNotVerified */ ($themeStyle=='horizontal') ? '<div class="custom-product-container">' : '<div class="custom-product-container-reverse">' ?>
            <!-- Product Images -->
            <?= /* @escapeNotVerified */ ($themeStyle=='horizontal' && $iterator%2==0) ? '<div class="left-column">' : '<div class="left-column-reverse">' ?>
                <?= $block->getImage($_product, 'product_page_image_medium')->toHtml() ?>
            </div>

            <?= /* @escapeNotVerified */ ($themeStyle=='horizontal' && $iterator%2==0) ? '<div class="right-column">' : '<div class="right-column-reverse">' ?>
                <!-- Product Description -->
                <div class="custom-product-description">
                    <h1><?= /* @escapeNotVerified */ $this->helper('Magento\Catalog\Helper\Output')->productAttribute($_product, $_product->getName(), 'name') ?></h1>
                    <p><?= /* @escapeNotVerified */ $this->helper('Magento\Catalog\Helper\Output')->productAttribute($_product, $_product->getDescription(), 'description') ?></p>
                </div>
                <!-- Product Pricing -->
                <div class="custom-product-price">
                    <span></span>
                    <a href="#" class="cart-btn">Add to cart</a>
                    <a href="javascript:void(0);" class="cart-btn open-quick-look-modal" data-pid="<?= /* @escapeNotVerified */ $_product->getEntityId() ?>">Quick Look</a>
                </div>
            </div>
        </div>
    <?php endforeach; ?>
<?php endif; ?>
</div>
<div id="js-quicklook-popup" style="display: none;">
    <iframe style="margin-top: 2vh" id="quicklook-iframe" width="100%" height="500px" frameborder="0" src=""></iframe>
</div>
<script>
    requirejs([
            'jquery',
            'Magento_Ui/js/modal/modal',
            'onepage_scroll'
        ],
        function($, modal) {

            $(document).ready(function() {
                if($("#custom-main-container").length) {
                    $("#custom-main-container").onepage_scroll({
                        sectionContainer: ".custom-product-container",
                        responsiveFallback: 600,
                        loop: true,
                        direction: "horizontal"
                    });
                }

                if($("#custom-main-container-reverse").length) {
                    $("#custom-main-container-reverse").onepage_scroll({
                        sectionContainer: ".custom-product-container-reverse",
                        responsiveFallback: 600,
                        loop: true,
                        direction: "vertical"
                    });
                }
                var options = {
                    type: 'popup',
                    responsive: true,
                    innerScroll: true,
                    modalClass: 'mybuttont_modal',
                    title: 'Quick Look',
                    buttons: [{
                        text: 'close',
                        class: '.m2express-quickview-close-btn',
                        click: function() {
                            this.closeModal();
                        } //handler on button click
                    }]
                };

                var popup = modal(options, $('#js-quicklook-popup'));
                $(".open-quick-look-modal").on('click',function(){
                    var productId = $(this).data('pid');
                    //$("#ql-product-name").html('test' + productId);
                    $("#quicklook-iframe").attr('src','/quicklook/display/view/id/' + productId);
                    $("#js-quicklook-popup").modal("openModal");
                });

            });
        }
    );
</script>