<?php
/**
 * Copyright © Magento2Express. All rights reserved.
 * @author: <mailto:contact@magento2express.com>.
 */
?>
<span data-bind="scope: 'quicklook'"><a href="javascript:void(0);" class="action toquicklook cart-btn open-quick-look-modal" data-bind="click: openQuickLookModal.bind(this,<?= $block->getProduct()->getEntityId(); ?>)" data-pid="<?= $block->getProduct()->getEntityId(); ?>">QuickLook</a></span>


